# -*- coding: utf-8 -*-
"""paytx.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h9o8OP-1fUWwxUkN9FztDehdM_85nSUG
"""

from dataclasses import dataclass
from decimal import Decimal
import time
from uuid import UUID, uuid4


# validates 'sender', 'receiver', and 'amount'.
# 'sender' and 'receiver' should look like real UPI ids.
# 0 < 'amount' <= 20000
# returns a pair of Tx object and None on success.
# returns (None, error) on failure.
def create_tx(sender, receiver, amount):
    if len(sender) == 0:
        return (None, "sender id is empty")
    if len(receiver) == 0:
        return (None, "receiver id is empty")
    if amount <= Decimal("0"):
        return (None, "amount is either zero or negative")
    if amount > Decimal("20000"):
        return (None, "amount is greater than the limit of Rs. 20000")
    #
    # validate sender id
    acc_bank = sender.split("@")
    if len(acc_bank) != 2:
        return (None, "invalid sender UPI id")
    sender_id = acc_bank[0].strip()
    sender_bank = acc_bank[1].strip()
    if len(sender_id) == 0 or len(sender_bank) == 0:
        return (None, "invalid sender UPI id")
    sender = sender_id + "@" + sender_bank
    #
    # validate receiver id
    acc_bank = receiver.split("@")
    if len(acc_bank) != 2:
        return (None, "invalid sender UPI id")
    receiver_id = acc_bank[0].strip()
    receiver_bank = acc_bank[1].strip()
    if len(receiver_id) == 0 or len(receiver_bank) == 0:
        return (None, "invalid receiver UPI id")
    receiver = receiver_id + "@" + receiver_bank

    #
    tx_ts = time.gmtime()
    tx_uuid = uuid4()
    #
    return (Tx(sender, receiver, amount, tx_ts, tx_uuid), None)


@dataclass
class Tx:
    sender: str
    receiver: str
    amount: Decimal
    ts: time.struct_time
    id: UUID

    @staticmethod
    def create(sender, receiver, amount):
        if len(sender) == 0:
            return (None, "sender id is empty")
        if len(receiver) == 0:
            return (None, "receiver id is empty")
        if amount <= Decimal("0"):
            return (None, "amount is either zero or negative")
        if amount > Decimal("20000"):
            return (None, "amount is greater than the limit of Rs. 20000")
        #
        # validate sender id
        acc_bank = sender.split("@")
        if len(acc_bank) != 2:
            return (None, "invalid sender UPI id")
        sender_id = acc_bank[0].strip()
        sender_bank = acc_bank[1].strip()
        if len(sender_id) == 0 or len(sender_bank) == 0:
            return (None, "invalid sender UPI id")
        sender = sender_id + "@" + sender_bank
        #
        # validate receiver id
        acc_bank = receiver.split("@")
        if len(acc_bank) != 2:
            return (None, "invalid sender UPI id")
        receiver_id = acc_bank[0].strip()
        receiver_bank = acc_bank[1].strip()
        if len(receiver_id) == 0 or len(receiver_bank) == 0:
            return (None, "invalid receiver UPI id")
        receiver = receiver_id + "@" + receiver_bank

        #
        tx_ts = time.gmtime()
        tx_uuid = uuid4()
        #
        return (Tx(sender, receiver, amount, tx_ts, tx_uuid), None)

    def __eq__(self, other) -> bool:
        return (
            type(other) is type(self)
            and self.amount == other.amount
            and self.sender == other.sender
            and self.receiver == other.receiver
        )

    def __str__(self):
        t = time.asctime(self.ts)
        return f"Tx({self.id} - From {self.sender} To {self.receiver}: Rs. {self.amount} on {t})"

    def strictly_before(self, other) -> bool:
        return type(other) is type(self) and self.ts < other.ts

    def on_or_before(self, other) -> bool:
        return type(other) is type(self) and self.ts <= other.ts


if __name__ == "__main__":
    print("main called...")
    (tx, err) = Tx.new("dprasadm@okhdfcbank", "dprasadm-1@oksbi", Decimal("100.23"))
    assert tx != None and err == None
    assert tx.amount == Decimal("100.23")
    ## try creating a tx the other way
    (tx1, err1) = create_tx(
        "dprasadm@okhdfcbank", "dprasadm-1@oksbi", Decimal("100.23")
    )
    assert tx1 != None and err1 == None
    assert tx1.amount == Decimal("100.23")
    assert tx.amount == tx1.amount
    assert tx.sender == tx1.sender
    assert tx.receiver == tx1.receiver
    assert tx == tx1
    assert tx.on_or_before(tx1)
    assert not tx.strictly_before(tx1)

    ##
    (tx2, err) = Tx.new("  abc  @mybank ", "  abc@xyz ", Decimal("1001.50"))
    assert tx2 != None and err == None
    assert tx2.amount == Decimal("1001.50")
    assert tx2.sender == "abc@mybank"
    assert tx2.receiver == "abc@xyz"
    ##
    (tx3, err) = Tx.new("dprasadm@okhdfcbank", "@mybank", Decimal("0"))
    assert tx3 == None and err != None
